[project]
name = "pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "img2pdf>=0.6.3",
    "pillow>=12.0.0",
    "pypdfium2>=5.1.0",
]

[dependency-groups]
dev = ["mypy>=1.19.0", "ruff>=0.14.8"]
